[package]
name = "hi_sparse_array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wide = "0.7.15"

[dev-dependencies]

